# Generated by Django 4.2.1 on 2023-05-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0003_alter_profile_user_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-updated"]},
        ),
        migrations.AddField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
