# Generated by Django 4.2.1 on 2023-06-13 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0007_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="liked_by",
            new_name="user",
        ),
    ]
